{% set name = "pyannote.database" %}
{% set version = "5.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyannote.database-{{ version }}.tar.gz
  sha256: b31f91af11bd4e12241dd7ade2efd562fa821f0f4d71f5dc4c54fbd5a5181a4b

build:
  noarch: python
  number: 0
  entry_points:
    - pyannote-database=pyannote.database.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pandas >=0.19
    - pyannote.core >=4.1
    - python >=3.8
    - pyyaml >=3.12
    - typer >=0.2.1

test:
  imports:
    - pyannote
    - pyannote.database
  commands:
    - pip check
    - pyannote-database --help
  requires:
    - pip

about:
  home: http://pyannote.github.io/
  summary: Interface to multimedia databases and experimental protocols
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tyrius02
