{% set name = "pyannote.database" %}
{% set version = "5.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyannote.database-{{ version }}.tar.gz
  sha256: 0eaf64c1cc506718de60d2d702f1359b1ae7ff252ee3e4799f1c5e378cd52c31

build:
  noarch: python
  number: 0
  entry_points:
    - pyannote-database=pyannote.database.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pandas >=0.19
    - pyannote.core >=4.1
    - python >=3.8
    - pyyaml >=3.12
    - typer >=0.2.1

test:
  imports:
    - pyannote
    - pyannote.database
  commands:
    - pip check
    - pyannote-database --help
  requires:
    - pip

about:
  home: http://pyannote.github.io/
  summary: Interface to multimedia databases and experimental protocols
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tyrius02
